#监听端口
listen: ":3030"

#http or https
scheme: "http"

#微信公众号App Id
appid: wxec9acece471f1e8e

#重定向URL的key字段
key_param: key

#重定向URL key-value映射
redirect_urls:
  prod: 'http://h5.tonglvhuanqiu.com/shop/',
  test: 'http://h5.test.tonglvhuanqiu.com/shop/#/',
  local: 'http://localhost:3001/shop/'